// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNoEI9rq-3OKyWQezdKLmoAzOClMEPpQ',
    appId: '1:728540480613:web:6efbd44db3abbbaf02328c',
    messagingSenderId: '728540480613',
    projectId: 'shms-d96ba',
    authDomain: 'shms-d96ba.firebaseapp.com',
    storageBucket: 'shms-d96ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJejno-hMeDIGw5Op-XSHBoYMd8RjeQo',
    appId: '1:728540480613:android:b294ddd43485fed102328c',
    messagingSenderId: '728540480613',
    projectId: 'shms-d96ba',
    storageBucket: 'shms-d96ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9sXXkhP6V9NCsHOM8dG00n3_Nwe3_gJM',
    appId: '1:728540480613:ios:99f9e703f96ad2cb02328c',
    messagingSenderId: '728540480613',
    projectId: 'shms-d96ba',
    storageBucket: 'shms-d96ba.firebasestorage.app',
    androidClientId: '728540480613-0qiu57dhhk4cv21ppp6n2ebccbcabfse.apps.googleusercontent.com',
    iosBundleId: 'com.project.healthManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9sXXkhP6V9NCsHOM8dG00n3_Nwe3_gJM',
    appId: '1:728540480613:ios:99f9e703f96ad2cb02328c',
    messagingSenderId: '728540480613',
    projectId: 'shms-d96ba',
    storageBucket: 'shms-d96ba.firebasestorage.app',
    androidClientId: '728540480613-0qiu57dhhk4cv21ppp6n2ebccbcabfse.apps.googleusercontent.com',
    iosBundleId: 'com.project.healthManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaNoEI9rq-3OKyWQezdKLmoAzOClMEPpQ',
    appId: '1:728540480613:web:358998430537cece02328c',
    messagingSenderId: '728540480613',
    projectId: 'shms-d96ba',
    authDomain: 'shms-d96ba.firebaseapp.com',
    storageBucket: 'shms-d96ba.firebasestorage.app',
  );
}
